### ISSUE TITLE
remove api会导致crash

### ISSUE THREAD

**Issue by bread2012** [fuxi-asyncflow/asyncflow#16]
重现方法：
1. 先调用异步函数的callback
2. 然后在同一个step里移除掉当前chart
原因：
1. 调用异步函数callback的时候，会把callback节点加到AsyncManager的activate_nodes里
2. remove当前chart的时候会依次析构掉当前chart的所有node（但没有移除位于AsyncManager里的node），并且把chart的agent赋值为nil
3. 下一次step的时候，当运行到调用async_manager_.Step()时，会遍历到已经析构掉的node，并且会访问已经析构掉的内存，调用node->GetAgent()，此时会返回nullptr，导致调用agent->RunFlow的时候直接crash

**Comment by fuxi-asyncflow** [comment]
确实，只考虑了节点析构的时候从 waiting_nodes_ 里面移除，没有处理节点已激活但还没运行时，位于 activate_nodes 里面的情况

**Comment by bread2012** [comment]
也不能直接从activate_nodes里移除吧，可能会出现一边遍历activate_nodes一边移除activate_nodes的情况；我想尝试给析构的node加个标记貌似也不太行，当内存复用的时候可能会造成逻辑错误。求大佬修下啊

**Comment by fuxi-asyncflow** [comment]
c51fb0849a76750e79b075e6cbeedccae61c6c31  看看这样ok不
